# Generated by Django 4.2.13 on 2024-05-26 22:27

from django.db import migrations, models
import django.db.models.deletion
from api import utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='current_region',
            field=models.ForeignKey(blank=True, default=utils.get_default_region, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='api.region'),
        ),
    ]
