# Generated by Django 4.2.13 on 2024-05-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_alter_score_score_ts_alter_score_value'),
        ('user', '0002_gameuser_current_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='current_region_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_current_region_scores', to='score.score'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_cheater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
