# Generated by Django 4.2.16 on 2024-10-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_gameuser_current_region_score_gameuser_is_banned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameuser",
            name="current_save",
            field=models.TextField(default=''),
        ),
    ]
