# Generated by Django 4.2.16 on 2024-11-25 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_gameuser_current_save"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameuser",
            name="referral",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
