# Generated by Django 4.2.16 on 2025-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_gameuser_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
