# Generated by Django 4.2.16 on 2025-03-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_gameuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='mvp_count',
            field=models.IntegerField(default=0),
        ),
    ]
