FROM nginx:latest

# Install Certbot
RUN apt-get update && \
    apt-get install -y certbot python3-certbot-nginx gettext

# Copy Nginx configuration template
COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template

# Copy the script to run Certbot and start Nginx
COPY init-letsencrypt.sh /init-letsencrypt.sh
RUN chmod +x /init-letsencrypt.sh

CMD ["/init-letsencrypt.sh"]
