# Generated by Django 4.2.14 on 2024-07-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infestation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_zombies_count', models.IntegerField(default=100)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infestations', to='api.region')),
            ],
        ),
    ]
