# Generated by Django 4.2.13 on 2024-05-18 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='score_ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 16, 32, 47, 112669, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='score',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.region'),
        ),
    ]
