# Generated by Django 4.2.13 on 2024-05-22 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_region_alter_score_score_ts_score_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 21, 9, 41, 513767, tzinfo=datetime.timezone.utc)),
        ),
    ]
