# Generated by Django 4.2.13 on 2024-05-23 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_score_score_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
