# Generated by Django 4.2.13 on 2024-05-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_score_score_ts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
