# Generated by Django 4.2.13 on 2024-05-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('score', '0005_alter_score_score_ts_alter_score_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.region'),
        ),
    ]
