# Generated by Django 4.2.13 on 2024-07-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_alter_score_score_ts_alter_score_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfestationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lower_bound', models.IntegerField(default=0)),
                ('upper_bound', models.IntegerField(default=9223372036854775807)),
            ],
        ),
    ]
