# Generated by Django 4.2.14 on 2024-07-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_infestationlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfestationLevel',
        ),
    ]
