# Generated by Django 4.2.16 on 2025-01-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infestation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infestation',
            name='start_zombies_ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
