# Generated by Django 4.2.16 on 2024-11-13 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_link', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('provider_token', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='XTR', max_length=3)),
                ('prices', models.JSONField()),
                ('photo_url', models.CharField(blank=True, default='', max_length=255)),
                ('photo_width', models.IntegerField(default=0)),
                ('photo_height', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
