# Generated by Django 4.2.16 on 2024-11-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('tg_buyer_id', models.CharField(max_length=255)),
                ('tg_payment_id', models.CharField(max_length=255)),
                ('is_receipt_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
