# Generated by Django 4.2.13 on 2024-05-25 13:12

from django.conf import settings
from django.db import migrations, models
import django.utils.datetime_safe

from api.utils import get_default_region


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='region',
            field=models.ForeignKey(default=get_default_region, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.region'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_dt', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='api.region')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='score.score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'region', 'score_dt')},
            },
        ),
    ]
