# Generated by Django 4.2.13 on 2024-05-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_score_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='points',
            new_name='value',
        ),
    ]
