# Generated by Django 4.2.13 on 2024-05-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_rename_points_score_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(),
        ),
    ]
