# Generated by Django 4.2.13 on 2024-05-28 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_alter_score_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
