# Generated by Django 4.2.16 on 2024-10-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("score", "0009_delete_infestationlevel"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["-value", "score_ts"], name="score_score_value_36f182_idx"
            ),
        ),
    ]
